raghusaripalli/GatorGiveaway

Sprint1.md

Hi Team, Added Sprint1.md file for today submission. Please add respective task status in the file. Also please add the API's with Rest Url and payload info.

Added Sprint1.md for today submission

---

frontend/src/components/Register/Register.js
frontend/src/index.js

frontend changes for Register call

Register API calling frontend changes

---

backend/webapp/views/auth.go

- Allowed user to use email to login
- Registration to check if the user email already exists

Add user email

---

backend/webapp/views/auth.go

- Allowed User to login using email or username
- Validated duplicated email check

Allowed user to login email, duplicate email check

---

backend/webapp/go.mod
backend/webapp/main.go
backend/webapp/user_test.go

- setup the backend testing skeleton

Setup test strucutre

---

frontend/package-lock.json
frontend/package.json
frontend/src/App.js
frontend/src/App.test.js
frontend/src/components/AboutUs/AboutUs.css
frontend/src/components/AboutUs/AboutUs.js
frontend/src/components/AboutUs/__test__/AboutUs.test.js
frontend/src/components/ContactUs/ContactUs.css
frontend/src/components/ContactUs/ContactUs.js
frontend/src/components/ContactUs/__test__/ContactUs.test.js
frontend/src/components/Footer/Footer.css
frontend/src/components/Footer/__test__/Footer.test.js
frontend/src/components/Header/Header.js
frontend/src/components/Header/__test__/Header.test.js
frontend/src/components/Login/Login.js

Hi Team,
Please review the jest unit test cases for UI interface. You can run them using npm-test command in root directory.
Thank You!

Added Jest Unit test cases for UI

---

frontend/src/App.js
frontend/src/components/ContactUs/ContactUs.js
frontend/src/components/Footer/Footer.js
frontend/src/components/Header/Header.js
frontend/src/components/Login/Login.js
frontend/src/components/Register/Register.js

Made UI changes using MUI library

Login, SigUp pages and Header, Footer UI changes

---

frontend/src/components/Footer/Footer.js
frontend/src/components/Header/Header.js
frontend/src/components/Header/__test__/Header.test.js
frontend/src/components/Home/Home.js
frontend/src/components/Login/Login.js

Made changes to home page product display card, added edit and delete icons, added about and logout in header and made changes to header test case accordingly to pass test.

Card_Icon_Header_changes

---

Sprint3.md

- Added Sprint3.md for updating the status of the sprint

Created a Sprint 3.md file

---

backend/webapp/main.go
backend/webapp/model/order.go
backend/webapp/views/orders.go

- Added API endpoint
- Migrated DB Tables Order and Post
- Validated corner cases like user login, JSON binding

Added API for placing an order

---

backend/webapp/main.go
backend/webapp/model/order.go
backend/webapp/views/orders.go

Added API for canceling the order. The user can cancel his orders then the backend will update the status of the order as canceled in the DB. (Checks for authorization). Closing the issue.

API for cancelling the user order

---

backend/webapp/model/product.go
frontend/src/components/Home/Home.js

HI Team,
Please review the code for adding fav icon in each product listing.

Included fav icon mui Widget in UI

---

frontend/src/App.js
frontend/src/components/Favorites/Favorites.js

Hi Team,
Please review the following changes for adding favorites tab.
Thank you!

Favorites seperate tab created and working completely

---

frontend/src/components/Header/Header.js
frontend/src/components/Header/__test__/Header.test.js

Hi team,
Please review the following changes for unit tests.
Thank you!

Added jest unit tests for header tab

---

frontend/src/App.js
frontend/src/components/Cart/Cart.js
frontend/src/components/Header/Header.js
frontend/src/components/Home/Home.js

Added add to cart for every post's card and at top nav bar to navigate to cart page

Cart added to post and top nav bar

---

backend/webapp/view_order_test.go

- Tests for the cancel order API
- success case
- user not login case
- invalid order id case

Cancel order api tests

---

frontend/src/components/Home/Home.js

When user clicks on add to cart, items get added to a cart that is displayed as a model by clicking cart fab button.

Display added cart items in a model

---

frontend/src/components/Home/Home.js

Display changes to showcase item image and number of items added to cart

Display changes to Cart page

---

frontend/src/components/Header/Header.js

Test case changes in HeaderTest

Test Cases changes

---

backend/webapp/main.go
backend/webapp/views/tags.go

Added API to retreive tags of a particular post.

Added API to retreive tags of a particular post. 

---

frontend/cypress/integration/deletepost.js
frontend/src/components/Login/Login.js

A new post gets add and by clicking delete icon post gets deleted.

Cypress test to delete post
